// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#include "textflag.h"

// Point the _crosscall2_ptr C function pointer at crosscall2, through a
// local trampoline so that the address of a dynamically exported
// function is never taken.
TEXT ·set_crosscall2(SB),NOSPLIT,$0-0
	MOVD	_crosscall2_ptr(SB), R1
	MOVD	$crosscall2_trampoline<>(SB), R2
	MOVD	R2, (R1)
	RET

TEXT crosscall2_trampoline<>(SB),NOSPLIT,$0-0
	JMP	crosscall2(SB)

// Called by C code generated by cmd/cgo.
// func crosscall2(fn, a unsafe.Pointer, n int32, ctxt uintptr)
// Calls cgocallback with three of those arguments; n is unused.
//
// Entered from C, so the arguments arrive in the out-registers and the
// local and in registers belong to the caller. SAVE opens a window for
// the Go code below to clobber and RESTORE hands the caller's back;
// after SAVE the arguments are in the in-registers, fn in R24, a in R25
// and ctxt in R27.
TEXT crosscall2(SB),NOSPLIT|NOFRAME,$0
	SAVE	$-208, RSP, RSP

	MOVD	R24, (176+0)(BSP)	// fn
	MOVD	R25, (176+8)(BSP)	// a
	MOVD	R27, (176+16)(BSP)	// ctxt

	CALL	runtime·load_g(SB)
	CALL	runtime·cgocallback(SB)

	RESTORE	ZR, ZR, ZR
	RET
